# -----------------------------------------------------------------------------
# - DOCKERFILE
# - AUTOR: Brian Suarez | Eduardo Franco | Jhon Celemin | Wilman Ortiz
# - FECHA: 06-Octubre-2020
# - DESCRIPCION: Docker-compose que permite la creacion del
# -              contenedor con el servicio de inicio de instancias en el bpm
# ------------------------------------------------------------------------------

version: '3.7'
services:
  bpm-command-services:
    image: bpm-command-services:latest
    container_name: bpm-command-services
    hostname: bpm-command-services
    restart: always
    ports:
      - 8082:8082
    networks:
      - ntw_backend
networks:
  ntw_backend:
    external: true